// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNiYVgzJKGzxo8GJbi4LH_u2TqDD1KCYY',
    appId: '1:947349636370:web:aeecfbae3663713f015fcb',
    messagingSenderId: '947349636370',
    projectId: 'balanced-meal-8cfaf',
    authDomain: 'balanced-meal-8cfaf.firebaseapp.com',
    storageBucket: 'balanced-meal-8cfaf.firebasestorage.app',
    measurementId: 'G-QVDFK1JKNL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyzY550Eb35Fu-RduwxsRzkCDDgCJWPOs',
    appId: '1:947349636370:android:efb73860f35bbe00015fcb',
    messagingSenderId: '947349636370',
    projectId: 'balanced-meal-8cfaf',
    storageBucket: 'balanced-meal-8cfaf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzXeJeRYHycmFzQDomfDNOlDp1af8zOeI',
    appId: '1:947349636370:ios:ff8bd52ff47faf2e015fcb',
    messagingSenderId: '947349636370',
    projectId: 'balanced-meal-8cfaf',
    storageBucket: 'balanced-meal-8cfaf.firebasestorage.app',
    iosBundleId: 'com.example.theGuard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzXeJeRYHycmFzQDomfDNOlDp1af8zOeI',
    appId: '1:947349636370:ios:ff8bd52ff47faf2e015fcb',
    messagingSenderId: '947349636370',
    projectId: 'balanced-meal-8cfaf',
    storageBucket: 'balanced-meal-8cfaf.firebasestorage.app',
    iosBundleId: 'com.example.theGuard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNiYVgzJKGzxo8GJbi4LH_u2TqDD1KCYY',
    appId: '1:947349636370:web:76f3252a29d8baea015fcb',
    messagingSenderId: '947349636370',
    projectId: 'balanced-meal-8cfaf',
    authDomain: 'balanced-meal-8cfaf.firebaseapp.com',
    storageBucket: 'balanced-meal-8cfaf.firebasestorage.app',
    measurementId: 'G-TQFEB7K867',
  );
}
